### PR TITLE
Fix mentioned users not getting notification on thread

### PR DESCRIPTION
**Pull request by thenav56**
Addresses
-  #636

### CODE REVIEW

**Review by sunu — APPROVED** [review]
@wrynearson Can you confirm that when users are mentioned, then only those mentioned users should get the notification and when no user is mentioned then the owner, the authors and the reviewers of the ATBD should get notifications?
If that's the desired behaviour, the changes look good to me!

**Comment by wrynearson** [comment]
Hey @sunu, please see the desired behavior on [this spreadsheet](https://docs.google.com/spreadsheets/d/1mjEzk_Zq0ZZhPPA8EoprrabXNf7lT5QxBcdS2QXqDQc/edit#gid=0&range=A22:C24) (rows 22-24). This is almost correct. When a thread (reply to a comment) is made, then the parent author of the comment should also be mentioned.

**Comment by thenav56** [comment]
Currently, we have two places where mentioned are used.
```python
backend/app/api/v2/threads.py
-- When new thread is created
187-    background_tasks.add_task(
188:        notify_atbd_version_contributors,
189-        atbd_version=atbd_version,
190-        notification="new_thread_created",
191-        atbd_title=atbd.title,
192-        atbd_id=atbd.id,
193-        user=user,
194-        data={"section": thread.section, "notify": thread.notify},
195-    )
196-
-- When a new comment is created
291-    background_tasks.add_task(
292:        notify_atbd_version_contributors,
293-        atbd_version=atbd_version,
294-        notification="new_comment_created",
295-        atbd_title=atbd.title,
296-        atbd_id=atbd.id,
297-        user=user,
298-        data={"section": thread.section, "notify": comment_input.notify},
299-    )
300-
```

## Is this what we want
- Thread
  - When mentioned: Only send to those users
  - When not mentioned: Send to the ATBD-RECEIVER
- Comment
  - When mentioned: Only send to those users (+comment's thread creator?)
  - When not mentioned: Send to the ATBD-RECEIVER, and comment's thread creator
> WHERE ATBD-RECEIVER = owner, authors, reviewers of ATBD

## Existing Behaviour
All notifications were sent to authors and reviewers(excluding the last one. Not sure why) by default,
https://github.com/NASA-IMPACT/nasa-apt/blob/78e1b06c30a01e025a31c8a8d8c675a2cc57c3b3/app/email/notifications.py#L45-L52
and if that was empty then to the owner and reviewer if exists.
https://github.com/NASA-IMPACT/nasa-apt/blob/78e1b06c30a01e025a31c8a8d8c675a2cc57c3b3/app/email/notifications.py#L75-L100

I am a bit confused with logic as well 🥲  , let me know if `Is this what we want` is what we are expecting.

**Comment by sunu** [comment]
> please see the desired behavior on [this spreadsheet](https://docs.google.com/spreadsheets/d/1mjEzk_Zq0ZZhPPA8EoprrabXNf7lT5QxBcdS2QXqDQc/edit#gid=0&range=A22:C24) (rows 22-24). This is almost correct. When a thread (reply to a comment) is made, then the parent author of the comment should also be mentioned.

@wrynearson In the spreadsheet, I think there is some confusion in wording in row 22 and 23. Comments are the children of a Thread. So I think the notification targets should probably be switched between row 22 and 23. Could you please clarify that?

**Review by sunu — CHANGES_REQUESTED** [review]
@thenav56 On a deeper look, we need some more changes.

1. The contents of the notification for mentioned users is different than the thread/comment creation notification. We might need to add a separate background task for notifying the mentioned users (if there are any) both while a thread is created or a comment is created.
2. The contents for comment mention notification needs to be added to[ email_templates.json](https://github.com/NASA-IMPACT/nasa-apt/blob/develop/app/email/email_templates.json). See row 24 in https://docs.google.com/spreadsheets/d/1mjEzk_Zq0ZZhPPA8EoprrabXNf7lT5QxBcdS2QXqDQc/ for the expected content.

This is in addition to fixing the implementation of `notify_atbd_version_contributors` so that it doesn't overwrite the supplied notification recipients in https://github.com/NASA-IMPACT/nasa-apt/blob/78e1b06c30a01e025a31c8a8d8c675a2cc57c3b3/app/email/notifications.py#L45-L52 

Here's what I think is the list of expected notifications and their recipients:
- Thread created:
  - Notification type `new_thread_created` to owner, authors and reviewers (From row 22 of the spreadsheet)
  - And, if users are mentioned: Notification type `comment_mention` to the mentioned users (From row 24 of the spreadsheet)
  
 - Comment created:
   - Notification type `new_comment_created` to owner and parent threads author (From row 23 of the spreadsheet)
   - And, if users are mentioned: Notification type `comment_mention` to the mentioned users (From row 24 of the spreadsheet)

**Comment by sunu** [comment]
> I am a bit confused with logic as well :smiling_face_with_tear: , let me know if Is this what we want is what we are expecting.

@thenav56 I don't understand the existing logic either tbh. I would suggest we try to match the spec instead of worrying too much about it.

**Comment by thenav56** [comment]
Thanks, @sunu

I have pushed changes according to the logic you mentioned. Having a different notification type `comment_mention` makes the logic more simplified.

Also, do we need to filter out the current user from the notifications?

**Comment by sunu** [comment]
Thanks @thenav56!
> Also, do we need to filter out the current user from the notifications?

Yes, good point! I think we should filter out the comment/thread author. My intuition is that a user won't like to receive a notification for a comment they themselves just created.

**Comment by thenav56** [comment]
Thanks, Skipping requesting users from the receipting list as well. https://github.com/NASA-IMPACT/nasa-apt/pull/637/commits/a4ade07fad7a2cd5e8d839bfc1e14713b1dd4511

**Comment by wrynearson** [comment]
Thanks @thenav56 and @sunu, and sorry for my confusion between comments and threads 😨. The logic written in these comments ☝️ seems correct to me. @sunu can give his final review before we merge it and test.

**Review by sunu — APPROVED** [review]
LGTM!

**Pull request merged**
