### PR TITLE
Add custom header with APT message

### PR DESCRIPTION
**Pull request by thenav56**
Upstream issue
- https://github.com/NASA-IMPACT/nasa-apt-frontend/issues/421#issuecomment-1831839480

Generated PDFs:
- Journal
Journal-patos-vv1.0-3.pdf](https://github.com/NASA-IMPACT/nasa-apt/files/13669406/Journal-patos-vv1.0-3.pdf)

- ~~Document~~
~~[patos-vv1.0.pdf](https://github.com/NASA-IMPACT/nasa-apt/files/13669405/patos-vv1.0.pdf)~~

### CODE REVIEW

**Comment by thenav56** [comment]
Just a note: the Line number also appears on the header of the journal. I will try to fix this, but if @sunu has any quick fix, let me know.

**Comment by thenav56** [comment]
> Just a note: the Line number also appears on the header of the journal. I will try to fix this, but if @sunu has any quick fix, let me know.

This is also fixed.

**Comment by wrynearson** [comment]
Sorry @thenav56, this should only be for the Journal PDF, not the Document PDF

**Comment by thenav56** [comment]
Hey @wrynearson, I have changed the logic to add header for Journal PDF only.

**Review by wrynearson — APPROVED** [review]
Perfect, thanks @thenav56!

**Pull request merged**
