### PR TITLE
Feature/update pdf error text

### PR DESCRIPTION
**Pull request by leothomas**
Update PDF error text: 
- Parses LaTeX error message to attempt to extract the specific error line(s)
- Adds full LaTeX error message in drop down

### CODE REVIEW

**Comment by leothomas** [comment]
Eg: 
image

**Comment by aboydnw** [comment]
@leothomas apologies I should have picked up on this before. Would it be possible to add a link to the feedback form in step #3? Also if there is any information they should include that would help troubleshoot after they have submitted the feedback form, we could call that out too. like "If this keeps happening, report your error through APT's feedback form and include the action you are trying to complete and the error information above"

Not sure if the additional instruction would be helpful, but at least a link to the feedback form would be nice.

**Comment by leothomas** [comment]
That's interesting - the feedback form in the application header isn't a link, but rather a pop-up form. I'm not sure how exactly that's configured and how we could integrate that to this error page.

@danielfdsilva is that possible?

**Comment by oliverroick** [comment]
@leothomas How can I test this?

**Comment by danielfdsilva** [comment]
This looks nice!

@oliverroick If you create a new doc and immediate try to generate the pdf it will fail because the "key points" field is missing.

@leothomas @aboydnw I reworded the error message and included a link to open the feedback form. It requires this [PR on the frontend](https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/356), but basically if `?feedback` is present in the url when opening the page, the popup will show up.

**Comment by leothomas** [comment]
@danielfdsilva I think "the action you are trying to complete" is a big vague, because this error only occurs during PDF generation. Can I re-word to: "please indicate the type of PDF you are trying to generate (journal vs regular) as well as the title and version number of the atbd"

**Comment by danielfdsilva** [comment]
@leothomas Totally right.
What of we include the type, version and atbd id as the first thing in the error? The we can just ask for the error and we'll know what the user did:

Something like
```
atbd/10/5.2.journal.pdf

Latex Error: ....
```

**Comment by leothomas** [comment]
It's a bit nit-picky, but I'd rather not insert that info the parsed the LaTex error block. How do you feel about something like: 
image

**Comment by leothomas** [comment]
For reference, here is the finalized approach with the ATDB identifying info as part of the parsed error message: 
image

**Review by danielfdsilva — APPROVED** [review]

**Pull request merged**
