### PR TITLE
Allow locked ATBD versions

### PR DESCRIPTION
**Pull request by oliverroick**
Contributes to https://github.com/NASA-IMPACT/nasa-apt/issues/454

- Adds new field `locked_by` to the versions table, we use that to store the user sub of the use that has currently locked the ATBD version
- Adds new API endpoint `/atbds/{atbd_id}/versions/{version}/lock`
  - Checks if the ATBD version is currently locked and by whom, returns HTTP 409 if another user has locked the ATBD version
  - Sets the lock otherwise and returns success response

### CODE REVIEW

**Review by leothomas — COMMENTED** [review]
I might be missing something, but should the functionality to relinquish the lock be implemented as well? Otherwise it seems like once the lock is set the API will forever return 409's for that version. 

Another concern: should there be a way to manually override the lock? (Eg: someone locks the version but forgets to unlock it before calling it a day, or even going on vacation, should the owner or even curator be allow to override the lock?)

Lastly, should all other updates for check if the version is locked before? If so, I think this can also be implemented in the ACL verification step. eg: 
`app/db/models/py#L123`
```python 
if action.get("status") and self.status not in action["status"]:
  continue

# add field `requires_unlocked` to ACLs for actions that CANNOT 
# be performed on LOCKED atbd versions
if action.get("requires_unlocked") and not self.locked_by: 
  # continue skips the rest of the loop iteration which grants the 
  # permissions for the requested action
  continue 
```

**Comment by oliverroick** [comment]
@leothomas Yes correct, these are all required to fully deliver the feature. I'm breaking this out into smaller junks, though, so the PR doesn't grow too big and to get feedback early.

**Comment by oliverroick** [comment]
@leothomas I added another commit to this PR to support the whole lock/unlock roundtrip. I'm sure there is a neater way to implement this, I just wanted to get something implemented for the frontend to consume. Feel free to completely rip this apart, even all the way to the API design, we can adapt the frontend. 

I've implemented three endpoints now, hoping this clarifies what we need:

- `/atbds/{atbd_id}/versions/{version}/lock` – This is used when the used opens the editor.
	- It checks whether the `locked_by` field is `None` or if the `sub` from user authenticated with the request matches the one in the `locked_by` field and returns a success response so the user can go ahead with edits. It also sets the `locked_by` field to the user's `sub`
	- If the previous condition isn't met, ie. the version is locked, then we return a `HTTP 409 Conflict` and display a warning to the user in the front-end
- `/atbds/{atbd_id}/versions/{version}/unlock` – This is used when a user unlocks a document. We present the user with a modal and an action to overwrite an existing lock. Calling this endpoint will get the `sub` from the user authenticated with the request and write that into the `locked_by` field. 
- `/atbds/{atbd_id}/versions/{version}/clearlock` — This is used when the user finishes editing, ie. leaves the editor. We send a request to this endpoint when the editor component is unmounted and set the `locked_by` field to `NULL`. I had to write a custom `set_lock` method for `CRUDVersions` because the `update` method of `CRUDBase` excludes `None` values. 

What I also haven't implemented yet is a way to check if the version is locked by the correct user when updating a version.

**Comment by leothomas** [comment]
A couple thoughts: 

The difference between `clearlock` and `unlock` isn't very clear to me. It seems like `unlock` essentially accomplishes what `clearlock` followed by `lock` would do, as long as the `clearlock` action doesn't check that the user requesting the operation is the same user as the `locked_by` user.

Typically HTTP API's expose resources, rather than actions. In my mind, the following design would make a bit more sense: 

```
# Note: all /lock endpoint actions are restricted to document collaborators (owner + author) and curator

GET /atbds/{atbd_id}/versions/{version}/lock
    - if locked_by is None: 
        - return 404 
   - if locked_by is not None: 
        - return 200 + locked_by
 
POST /atbds/{atbd_id}/versions/{version}/lock
    - if locked_by == user.sub or locked_by is None:
        - set locked_by to user.sub
        - return 200, locked_by  
    - if locked_by is not None and locked_by != user.sub:
        - return 409 Conflict

POST /atbds/{atbd_id}/versions/{version}/lock?action=unlock
    - if locked_by == user.sub or locked_by is None: 
        - set locked_by to None
        - return 200
    - if locked_by is not None and locked_by != user.sub: 
        -  return 409 Conflict
   
POST /atbds/{atbd_id}/versions/{version}/lock?action=unlock&override=True
     - set locked_by to None
     - return 200
```

In this way we expose the `lock` as a resource and perform actions on the resource (locking/unlocking/overriding) as POST requests to the resource. I've assumed that the default operation when POSTing to the `lock` resource is to lock (rather than unlock), but we can also require the `action` flag to be present in both cases for clarity. 

I think we have to be careful with the `override` flag however. Allowing any user (or at least any author/owner/curator) to override the lock might create a condition where user A locks the document, works on it for super long, user B overrides the lock and then user A looses their work. At the very least it would require a modal or warning to pop up, informing the user that this action might cause other users to loose their work + a confirmation step. 

Let me know your thoughts on the above, and I can move to implementation

**Comment by leothomas** [comment]
A couple more thoughts: 
- We can restrict the use of the `override` flag to only certain users, for example: curators and/or the document owner 
- We can change the action values to `request` and `release`, instead of the empty/default and `unlock` values, as the combination of the works "lock" and "unlock" within a single URL might be confusing:  
```
/{versionId}/lock?action=request
/{versionId}/lock?action=release
```
vs
```
/{versionId}/lock
/{versionId}/lock?action=unlock
```

**Comment by leothomas** [comment]
Change error message content to include email and name when conflict arises

**Comment by chuckwondo** [comment]
@leothomas, if your intent is to expose locks as resources, then I would think that you would want to release a lock via DELETE, not with a POST + query param. Is there anything that would prevent you from using DELETE?

**Comment by leothomas** [comment]
That's a great point @chuckwondo! Since placing the lock and removing it are idempotent requests, we could just use `PUT` and `DELETE`. This solves 2 things I was unsure about: the use of `action` as a request parameter feels a bit like an antipattern, and I didn't know whether the `override: bool` flag should be a query (URL) parameter or request (body) parameter

**Comment by leothomas** [comment]
In the version update specification, we keep track of the last user that updated the ATBD Version (`last_updated_by`) and at what date/time (`last_updated_at`). Should locking the ATBD Version update these values?

**Comment by oliverroick** [comment]
@leothomas 

> In the version update specification, we keep track of the last user that updated the ATBD Version (last_updated_by) and at what date/time (last_updated_at). Should locking the ATBD Version update these values?

I don't think so. Locking/unlocking a version isn't technically an update.

**Comment by oliverroick** [comment]
Superseded by #516

**Pull request closed without merging**
