### PR TITLE
Add version description to ATBD list view

### PR DESCRIPTION
**Pull request by oliverroick**
Contributes to https://github.com/NASA-IMPACT/nasa-apt/issues/527

Adds the `version_description` to the API list view of ATBDs

### CODE REVIEW

**Comment by naomatheus** [comment]
I am getting an error from the frontend a null version description.
```
TypeError: Cannot read properties of undefined (reading 'version_description')
(anonymous function)
/__parcel_source_root/app/assets/scripts/components/documents/document-changelog-modal.js:43:26
  40 | <Version key={version}>
  41 |   <h3>{version}</h3>
  42 |   <SafeReadEditor
> 43 |     value={document.version_description}
     |                    ^  44 |     whenEmpty='No summary available'
  45 |   />
  46 |   <Downloads>
```

**Review by naomatheus — COMMENTED** [review]
I am getting an error from the frontend a null version description.
```
TypeError: Cannot read properties of undefined (reading 'version_description')
(anonymous function)
/__parcel_source_root/app/assets/scripts/components/documents/document-changelog-modal.js:43:26
  40 | <Version key={version}>
  41 |   <h3>{version}</h3>
  42 |   <SafeReadEditor
> 43 |     value={document.version_description}
     |                    ^  44 |     whenEmpty='No summary available'
  45 |   />
  46 |   <Downloads>
```

**Comment by oliverroick** [comment]
@naomatheus The error looks like the `document` itself was `undefined`, not the version description. I just tested this again with latest `develop` of the front-end and it seems to work ok both for documents that have a version description and for documents that don't.

Do you have the steps you took to reproduce this?

**Comment by naomatheus** [comment]
Process to review was:
- Create a new directory, close any currently running docker-compose instance of APT
- Pull down this specific branch
- Run `docker-compose up --build --force-recreate -d` to force rebuild of the image
- Wait for `localstack` container to stabilize, and run `docker exec -it [CONTAINER_ID] bash` to "ssh" in
- Run the scripts from APT local development guide, the scripts that get the PoolId and ClientId for frontend's `local.js`
- Pull `develop` or the co-testing branch from `nasa-apt-frontend`
- Fill in the variables for `local.js` file
- Run `yarn serve` to open the frontend
- Test for the change/feature

**Comment by naomatheus** [comment]
This worked for me this time! I pulled the latest develop into the `list-version-description` branch and merged it. And now I can observe the addition without errors.

**Review by naomatheus — APPROVED** [review]
Passes review. Approving.

**Review by naomatheus — APPROVED** [review]
Passes review. Approving.

**Pull request merged**
