### PR TITLE
Feature/pdf improvements

### PR DESCRIPTION
**Pull request by leothomas**
This PR implements the following features requested in issue #474 : 
|       | Before | Now | PDF Type |
| --- | ------ | ----- | ----------|
| 1.   | PDF displays date generated | PDF displays no date if `status` is not `published` otherwise displays the `published at` date | Regular |
| 2.   | No page break after TOC | Page break after TOC | Regular |
| 3.   | No heading in PDF | Heading in PDF (says: `This ATBD was downloaded from the NASA Algorithm Publication Tool (APT)` | Regular |
| 4.  | Centered heading in PDF only displays: `Manuscript submitted to _Earth and Space Science_` | Centered heading in PDF displays: `Manuscript submitted to _Earth and Space Science_ \n This ATBD was downloaded from the NASA Algorithm Publication Tool (APT)` | Journal |

Screenshots: 
## No date in un-published regular PDF: 
image

## Date in published regular PDF: 
image

## Page break after TOC in regular PDF: 
image

### Title page:
image

### Other page: 
image

### Title page: 
image

### Other page: 
image

### CODE REVIEW

**Comment by leothomas** [comment]
Full sample documents: 
- Regular PDF, published: [test-atbd-1-v2-0.pdf](https://github.com/NASA-IMPACT/nasa-apt/files/8454138/test-atbd-1-v2-0.2.pdf)
- Journal PDF, _un_published: [test-atbd-1-v2-0-journal.pdf](https://github.com/NASA-IMPACT/nasa-apt/files/8454137/test-atbd-1-v2-0-journal.pdf)

**Comment by aboydnw** [comment]
@leothomas do you have a screenshot that shows the date of a pdf that was published before today? I think one of the main issues here was people were generating pdfs and they would always just have the current date

**Comment by leothomas** [comment]
I could generate one by changing the date manually in the database - let me give that a try

**Comment by leothomas** [comment]
Regular PDF with publication date (note current date in top right corner)
image

**Review by aboydnw — APPROVED** [review]
The output looks good to me!

**Comment by danielfdsilva** [comment]
@leothomas The proposed changes look good. I found some other issues that may not be related, but leaving them here.
For this I was looking at the `Test ATBD 1 v2.0` (fixture data).

Even though the links do not overflow the page anymore, they still overflow onto the margins. Is there something to be done here? Does not seem like a big problem, but flagging.
image
image


**journal pdf only**
Spaces are stripped from links that have multiple words.  

image

**Comment by leothomas** [comment]
@danielfdsilva Thanks for pointing those out. I'm going to merge this PR and open issues for the links

**Pull request merged**
