### PR TITLE
Update diagram/issue 710

### LINKED ISSUE #710: Update AWS Architecture Diagram
We should update our AWS Architecture Diagram. IMPACT is hoping to have it as soon as possible (this sprint if possible, or next sprint).

- [x] Find existing AWS Architecture diagram
- [x] Update AWS Architecture Diagram

cc @sunu @batpad

### PR DESCRIPTION
**Pull request by naomatheus**
Closes https://github.com/NASA-IMPACT/nasa-apt/issues/710

APT-infrastructure
updates the architecture diagram for APT application
#710  

There is a JPEG stored within the ADR directory and also an editable file that can be opened with the draw.io web application

### CODE REVIEW

**Review by sunu — COMMENTED** [review]
@naomatheus This diagram looks fantastic! Just a couple of questions/suggestions:

- It seems the diagram is missing the part where the lambdas interact with S3 buckets, like when they save PDFs or deliver them to users. Adding that in would be great!
- We are moving the OpenSearch instance into the VPC in https://github.com/NASA-IMPACT/nasa-apt/pull/703/. Is there a specific reason to have it in a public subnet instead of a private one? By the way, this PR also includes changes from #703. If possible, let's kindly remove those extra commits from this PR to keep things tidy!

**Comment by wrynearson** [comment]
@naomatheus are you able to reply to @sunu's comments, or should @sunu finish this PR?

**Comment by naomatheus** [comment]
Opening for review and merge

**Comment by naomatheus** [comment]
> * We are moving the OpenSearch instance into the VPC in [IN REVIEW: support moving opensearch domain into the VPC #703](https://github.com/NASA-IMPACT/nasa-apt/pull/703). Is there a specific reason to have it in a public subnet instead of a private one? By the way, this PR also includes changes from [IN REVIEW: support moving opensearch domain into the VPC #703](https://github.com/NASA-IMPACT/nasa-apt/pull/703). If possible, let's kindly remove those extra commits from this PR to keep things tidy!

Sounds good @sunu. I've cleaned up this PR to only cover diagram issues. 
I will then move to clean up PR #703 to remove any extra commits.

Here is the updated diagram
APT-infrastructure


**Note:**  This PR may not pass linting checks, but that is OK because this PR only contains the diagram ADR.

**Review by sunu — APPROVED** [review]
Thanks @naomatheus! 🙌🏽

**Pull request merged**
