### PR TITLE
update doc strings, linting

### PR DESCRIPTION
**Pull request by naomatheus**
Updated doc strings, and other linting

### CODE REVIEW

**Comment by naomatheus** [comment]
I think this linting error might prevent even this PR.

```
mypy.....................................................................Failed
- hook id: mypy
- exit code: 1

app/email/notifications.py:44: error: Expected keyword arguments, {...}, or dict(...) in TypedDict constructor
Found 1 error in 1 file (checked 68 source files)
```

Does anyone have any ideas as to how to resolve this? When looking it seems that the requirements the linter mentions here are already fulfilled in the notifications module.

**Review by TimMcCauley — APPROVED** [review]
lgtm!

**Comment by TimMcCauley** [comment]
> I think this linting error might prevent even this PR.
> 
> ```
> mypy.....................................................................Failed
> - hook id: mypy
> - exit code: 1
> 
> app/email/notifications.py:44: error: Expected keyword arguments, {...}, or dict(...) in TypedDict constructor
> Found 1 error in 1 file (checked 68 source files)
> ```
> 
> Does anyone have any ideas as to how to resolve this? When looking it seems that the requirements the linter mentions here are already fulfilled in the notifications module.

It looks like this change 

Screenshot 2022-08-12 at 17 16 30

is effecting the typed dict ➡️  https://github.com/NASA-IMPACT/nasa-apt/blob/develop/app/email/notifications.py#L18 - can you check what is being used to construct `UserNotification` ?

**Comment by leothomas** [comment]
I'm not 100% sure why I had ignored that error (see: `# type: ignore`) the first time around, but the quick and dirty fix is to add that `# type: ignore` comment back on line 44 

I just ran it and it passes the tests locally

**Pull request merged**
