### PR TITLE
Make sure anonymous users can download published ATBDs

### PR DESCRIPTION
**Pull request by sunu**
Published ATBDs are public. So anonymous users should be able to download them.

### CODE REVIEW

**Comment by wrynearson** [comment]
@batpad or @thenav56 – would you have time to review this by the end of the week? If not, no worries

**Review by thenav56 — APPROVED** [review]
The anonymous download is working.

Not sure if this is related but with authenticated user I am getting this error in the workers log
```
backend-worker-1  | INFO:app.logs:Generating PDF
backend-worker-1  | ERROR:app.logs:Error handling task: {'task_type': 'make_pdf', 'payload': {'atbd': <Atbds(id=1, title=Test ATBD 1, alias=test-atbd-1, created_by=82d6a663-cd07-40e3-abcc-214c2de1d302, created_at=2023-03-23 01:55:18.550710+00:00, last_updated_by=82d6a663-cd07-40e3-abcc-214c2de1d302, last_updated_at=2023-03-23 01:55:18.550710+00:00 versions=v2.0)>, 'filepath': '1/pdf/test-atbd-1-v2-0-3fa6f891d09334c4d46ac2ba1635d68a.pdf', 'major': 2, 'minor': 0, 'auth_data': {'id_token': '', 'access_token': None, 'user_email': 'curator@apt.com'}}}
backend-worker-1  | Traceback (most recent call last):
backend-worker-1  |   File "/app/app/worker.py", line 56, in worker
backend-worker-1  |     handle_task(task)
backend-worker-1  |   File "/app/app/worker.py", line 31, in handle_task
backend-worker-1  |     handler(**task_payload)
backend-worker-1  |   File "/app/app/pdf/utils.py", line 61, in make_pdf
backend-worker-1  |     context = browser.new_context(storage_state=storage_state)
backend-worker-1  |   File "/app/playwright/sync_api/_generated.py", line 13917, in new_context
backend-worker-1  |     self._sync(
backend-worker-1  |   File "/app/playwright/_impl/_sync_base.py", line 104, in _sync
backend-worker-1  |     return task.result()
backend-worker-1  |   File "/app/playwright/_impl/_browser.py", line 127, in new_context
backend-worker-1  |     channel = await self._channel.send("newContext", params)
backend-worker-1  |   File "/app/playwright/_impl/_connection.py", line 44, in send
backend-worker-1  |     return await self._connection.wrap_api_call(
backend-worker-1  |   File "/app/playwright/_impl/_connection.py", line 419, in wrap_api_call
backend-worker-1  |     return await cb()
backend-worker-1  |   File "/app/playwright/_impl/_connection.py", line 79, in inner_send
backend-worker-1  |     result = next(iter(done)).result()
backend-worker-1  | playwright._impl._api_types.Error: storageState.origins[0].localStorage[1].value: expected string, got object
backend-worker-1  | INFO:app.logs:Handling task: {'task_type': 'make_pdf', 'payload': {'atbd': <Atbds(id=2, title=Project algorithms technically overly simplistic, alias=patos, created_by=82d6a663-cd07-40e3-abcc-214c2de1d302, created_at=2021-03-14 14:30:00+00:00, last_updated_by=82d6a663-cd07-40e3-abcc-214c2de1d302, last_updated_at=2021-03-15 16:00:00+00:00 versions=v1.0)>, 'filepath': '2/pdf/patos-v1-0-31d2634d115a25f791136696f6bb7d99.pdf', 'major': 1, 'minor': 0, 'auth_data': {'id_token': '', 'access_token': None, 'user_email': 'curator@apt.com'}}}
```

**Comment by sunu** [comment]
@thenav56 Looks like authorization headers are missing in that requests: ` 'auth_data': {'id_token': '', 'access_token': None, 'user_email': 'curator@apt.com'}`. Can you check the headers for the request?

I will add an explicit check for missing headers.

**Comment by thenav56** [comment]
Hi @sunu 

Now the error is showing about `Missing authorization headers`.
Basically, as a curator@apt.com account I followed this steps
- Started from scratch. `docker-compose down` and `docker-compose up db bootstrapper localstack api` 
- Clicked Download for document http://localhost:9000/documents/test-atbd-1/v2.0
  - v2.0 Journal PDF is failing due to missing `text` key. Maybe issue with bootstrap data
  - v2.0 Document PDF is showing `Missing authorization headers issue`
     - This is the link it gets forwared to [LINK](http://localhost:8000/v2/atbds/1/versions/v2.0/pdf?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsImtpZCI6InRlc3Qta2V5In0.eyJleHAiOjE2Nzk5ODI4NzIsImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6NDU2Ni91cy1lYXN0LTFfNjc3MTY1NTZkMWExNDkxNTk5Y2FhNDI0NDc1ZmI1MzIiLCJzdWIiOiIxZTgyMWEyMC1iN2I5LTRjNjItOTM5Yi1mMDVmOTBlYzlmNGIiLCJhdXRoX3RpbWUiOjE2Nzk4OTY0NzIsImlhdCI6MTY3OTg5NjQ3MiwiZXZlbnRfaWQiOiJiNTE4OWZmMS00MjljLTRlZTktOGYzMy0zNzZjYjM4NWQ4NDYiLCJ0b2tlbl91c2UiOiJpZCIsImVtYWlsIjoiY3VyYXRvckBhcHQuY29tIiwiYXVkIjoiN2Qxd3NwYTZma2dmZWx0ZWZoaHNudmxiaXgiLCJjb2duaXRvOmdyb3VwcyI6WyJjdXJhdG9yIl0sImVtYWlsX3ZlcmlmaWVkIjoidHJ1ZSIsInByZWZlcnJlZF91c2VybmFtZSI6IkNhcmxvcyBDdXJhdG9yIiwiY29nbml0bzp1c2VybmFtZSI6IjFlODIxYTIwLWI3YjktNGM2Mi05MzliLWYwNWY5MGVjOWY0YiJ9.aeKYsS4Z4HhQHIsm7Gi8-0FfScdG84wJlNExIwMhw-bIiioqphAzAf042DzKQnVZJl6tXE1D32GZ1qwTy14XxOTWZ-3YkKIV4LXjn4c9Q0wpCvFSsSEWeLgleeAGV9cpYCvYNPoOcG8J7BfMYgNNwq4w1GDLWKbczle06PFmrITx1q8ExxCQrKFhNBedrUrX7WUhrGo2zPv59yOo-5RY1uA6h0irBWvTzjGQicKEsuQxDzkVm5Jm4oIPX0xJ51u9JwgpQRvmUjG2T2orwCh7gbLolVKssntBHeOB8U2GvbrbWZk_b87ui1Ubf2kFEfVXknopYyuihEkaJBfB7cbozQ) which has the token as GET param.

Also, typo in app/api/v2/pdf.py
https://github.com/NASA-IMPACT/nasa-apt/blob/29d185d98dc3ef69648a1fc543b5c710a67ccdea/app/api/v2/pdf.py#L174

Logs
For `text` key
```
backend-api-1           | During handling of the above exception, another exception occurred:
backend-api-1           |
backend-api-1           | Traceback (most recent call last):
backend-api-1           |   File "/app/./app/api/v2/pdf.py", line 155, in get_pdf
backend-api-1           |     local_pdf_filepath = generate_pdf(
backend-api-1           |   File "/app/./app/pdf/generator.py", line 982, in generate_pdf
backend-api-1           |     raise e
backend-api-1           |   File "/app/./app/pdf/generator.py", line 979, in generate_pdf
backend-api-1           |     latex_document = generate_latex(atbd, filepath, journal=journal)
backend-api-1           |   File "/app/./app/pdf/generator.py", line 713, in generate_latex
backend-api-1           |     output = prepare_sections.prepare_sections(
backend-api-1           |   File "/app/./app/pdf/prepare_sections.py", line 29, in prepare_sections
backend-api-1           |     "contents": fill_contents.fill_contents(
backend-api-1           |   File "/app/./app/pdf_utils/fill_contents.py", line 67, in fill_contents
backend-api-1           |     contents.append(process_lists.ul_ol_lists(element))
backend-api-1           |   File "/app/./app/pdf_utils/process_lists.py", line 29, in ul_ol_lists
backend-api-1           |     for item in list_items(child):
backend-api-1           |   File "/app/./app/pdf_utils/process_lists.py", line 18, in list_items
backend-api-1           |     return [d["text"] for _indx, d in enumerate(items)]
backend-api-1           |   File "/app/./app/pdf_utils/process_lists.py", line 18, in <listcomp>
backend-api-1           |     return [d["text"] for _indx, d in enumerate(items)]
backend-api-1           | KeyError: 'text'
```

**Comment by sunu** [comment]
@thenav56 thanks for spotting the typo. Can you check which commit you're on for the frontend? The latest one should use auth headers instead of a token as query param.

**Comment by thenav56** [comment]
Thanks, @sunu. The token issue is solved by using the latest client. Sorry about that.

**Comment by wrynearson** [comment]
@thenav56 @sunu once you guys think this is ready, one of you can merge it 😄

**Pull request merged**
