### PR TITLE
Convert plain_summary and abstract to rich-text field

### PR DESCRIPTION
**Pull request by oliverroick**
Contributes backend changes for https://github.com/NASA-IMPACT/nasa-apt-frontend/issues/331

- Changes `abstract` and `plain_summary` so they accept rich-text objects
- Updates test data from plain text to rich-text object

These changes can be tested by:

- Applying the test data, and
- Running the [corresponding front-end changes](https://github.com/NASA-IMPACT/nasa-apt-frontend/pull/359) against it

### CODE REVIEW

**Comment by leothomas** [comment]
I think this might cause issue with existing data, since `abstract` and `plain_summary` fields for atbd versions already in the database will be returned to the API as `type: str` and pydantic will try to build them as `type: SectionWrapper`. 

I think this should be done using a sqitch migration. I'll try to find/put together some code snippets

**Comment by leothomas** [comment]
Got it. My understanding, based on convos from a couple months ago, was that the dev stack (`nasa-apt.surge.sh`, backend in Dev Seed AWS) would have no expectation of data permanence, and once the new features are validated in dev, they get pushed to the prod stack (backend in MCP) whose database will be cleared in order to import data from the old prod backend (in UAH). Once the data is migrated from UAH to MCP, the UAH stack would be dropped entirely.

In this case, the data in UAH would need to be updated with `type:SectionWrapper` fields for `abstract` and `plain_summary` before being migrated to MCP. _However_ if you have had more a recent conversation with Impact and they're clear on not needing any of the data in UAH (I would suggest confirming this in writting), then we can go ahead and merge this feature. 

> (Although, admittedly, this is one of those situations where someone who wasn't involved in the decision will ask where their document is – maybe we should migrate to be on the safe side)

From my experience, this very probable, or a situation where Impact team doesn't have the consensus they think they do as to what exact "not necessary to retain existing data" actually means (should the data be stored somewhere for backup? Is it just the `abstract` and `plain_summary` fields that don't need to be retained, but the rest should be? Should all of the atbds be retains, but not versions? etc)

**Comment by oliverroick** [comment]
> From my experience, this very probable, or a situation where Impact team doesn't have the consensus they think they do as to what exactly "not necessary to retain existing data" actually means (should the data be stored somewhere for backup? Is it just the abstract and plain_summary fields that don't need to be retained, but the rest should be? Should all of the atbds be retains, but not versions? etc)

If we do a migration the we should probably just migrate whatever needs to be migrated. How big a lift do you think this is? When I updated the test data I only needed to wrap the existing text in an object like so:

```
{"abstract": {"children": [{"type": "p", "children": [{"text": "Existing text"}]}]}
```

Scripting this should be doable, shouldn't it?

**Comment by leothomas** [comment]
@oliverroick I added SQL scripts for deploying/reverting the updated `abstract` and `plain_summary` fields of the document column. 

### To test: 
1. Check out the `develop` branch
2. Clear out any existing volumes that may have cached database data (`docker-compose down --volumes`)
3. Build and start up the API (`docker-compose up`) 
4. Verify that `abstract` and `plain_summary` are plain text values
5. (With the API still running) checkout the `summary-rich-text` branch
6. Run the `abstract` + `plain_summary` update (`sqitch deploy --verify db:pg://masteruser:password@localhost:5432/nasadb`)
7. Verify that the `abstract` and `plain_summary` fields are now rich text values (if not null)

### Notes: 
This update will require an update from the frontend to submit the `abstract` and `plain_summary` fields as rich text to the database + consume them as rich text fields from the database

**Comment by oliverroick** [comment]
@leothomas The migrations work as expected, thanks! 

Can you approve the PR when you have a moment so we can merge?

**Review by leothomas — APPROVED** [review]

**Pull request merged**
